# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that.

# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# You can access these config variables using {{ site.variablename }}.

url    : ""     # the base hostname & protocol for your site, e.g. http://example.com
baseurl: ""    # the subpath of your site, e.g. /blog
gstturl: "https://www.guysandstthomas.nhs.uk/"

title      : CSC
email      : cscteam@gstt.nhs.uk
description: "Clinical Scientific Computing"
author     : CSC

locale: "en-US" # See available languages in _data/sitetext.yml

include: [_pages]

collections:
  team_member:
    output: true
  platforms:
    output: true
  projects:
    output: true
  handbook:
    output: true
  resources:
    output: true
  communities:
    output: true
  guides:
    output: true
  fellow:
    output: true
markdown: kramdown
